excluded:
  - .build
  - .swiftpm
  - Package.swift
  - ./*/Package.swift
  - ./*/Tests
  - QuesterTests/
  - QuesterUITests/

disabled_rules:
    - todo
    - blanket_disable_command
    - non_optional_string_data_conversion

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - file_header
  - force_unwrapping
  - implicit_return
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - period_spacing
  - redundant_nil_coalescing
  - redundant_type_annotation
  - shorthand_optional_binding
  - sorted_imports
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  
analyzer_rules:
  - unused_import

line_length:
    warning: 200
    error: 280
    ignores_function_declarations: true
    ignores_comments: true
    ignores_interpolated_strings: true
    ignores_urls: true
    
file_length:
    warning: 400
    error: 500

function_body_length:
    warning: 80
    error: 100

type_body_length:
    warning: 350
    error: 450

type_name:
    allowed_symbols: "_"
    max_length:
        warning: 50
        error: 60
        
implicit_return:
    included: [closure, function]

force_cast: warning
force_try: warning

cyclomatic_complexity:
  ignores_case_statements: true

reporter: "xcode"
